travis:
  secure:
    BINSTAR_TOKEN: LIiSi+0S/c3czqx6h/CGtUrKemuG+mCOiSdRaS4CGI3+vv3E1SIEqS2PZkIfB/skGjeKki82yZ1WOqzaoYgvmWiBRfr0OgJGpOjeBG9vQzlP7ujdJRQKjaoSsbWaa4AycIIMmcNlL5WzbTIidSNMX7Q92dxWsQp9GunY12L+ROfURPbw4DoyHw+RwWNNlzKweIvv6djmmnw9FFFZmlQ/+0FYEZckLY8P4JA0De9WaAwYwFCu70BjkH+LXVA0Y0BYRYGCRe6OZvrUUhEpQxkdpC9eyTqwpVM83ARUt8V0vjFoRVQ2cIO/1MocIuj4HVHZH1cR2MlVDpUrgUCJi0s3FxxDHPc56JsG1cwKw0jXfxGYby04LQCUnbXHPgFUxuw5cUFkie+TRDQtpw22BaKcY5Cr73PFIBWZi7lvHeUj9vIIuSB1VhbRPHLX1TfbGFLltRieMx7K9r0VTJS7YNGRYuO3ViVxlsb1ZzAGo2c8419HyqywAxMeBWB+R6UAcDvXUdMaMtpKfPYg77/2PN1hvQIQxh+D037rnh/NxTDbV9siXrOg7NGnAKHn8NUqP7Qgch+gNaZWmdU7ubCQ0IPlvJP6BkOMNnj4tJ3BgOK0YjLbOaaFNXO9N5ZwwAzkezOGPW2iGejXrK+lP5DD4fm7PD/W7miOjfIusGt2gagmrtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
